services:
  react-app:
    build: .
    ports:
      - '3005:80' # Контейнер работает на 3005-м порту, но внутри все так же на 80-м
    restart: always
    networks:
      - my_network

networks:
  my_network:
    external: true
