name: CI/CD Pipeline

on:
  push:
    branches:
      - master # или main, если ты используешь другую ветку
  pull_request:
    branches:
      - master

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test -- --watchAll=false

  deploy:
  name: Deploy to Server
  needs: test
  runs-on: ubuntu-latest

  steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up SSH
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan github.com >> ~/.ssh/known_hosts

    - name: Deploy via SSH
      uses: appleboy/ssh-action@v0.1.7
      with:
        host: 88.218.168.129
        username: root
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
          echo "Переходим в каталог проекта"
          cd /var/www/mywebsite/my-test-cicd || exit 1

          echo "Выводим текущий коммит перед обновлением"
          git rev-parse HEAD

          echo "Сбрасываем все изменения и обновляем код"
          git reset --hard HEAD
          git pull origin master

          echo "Останавливаем и удаляем старые контейнеры"
          docker-compose down

          echo "Удаляем старые образы"
          docker system prune -af

          echo "Пересобираем и запускаем контейнеры"
          docker-compose up --build -d

          echo "Деплой завершен"
