name: CI/CD Pipeline

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test -- --watchAll=false

  deploy:
    name: Deploy to Server
    needs: test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      # Логирование текущей директории для отладки
      - name: Print current directory and list files
        run: |
          pwd
          ls -la

      # Проверка наличия docker-compose.yml
      - name: Check if docker-compose.yml exists
        run: |
          if [ -f "docker-compose.yml" ]; then
            echo "docker-compose.yml found"
          else
            echo "docker-compose.yml not found" && exit 1
          fi

      # Подключение к серверу через SSH и деплой
      - name: Deploy via SSH
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: 88.218.168.129
          username: root
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            echo "Переходим в каталог проекта"
            cd /var/www/mywebsite/my-test-cicd || exit 1

            echo "Выводим текущий коммит перед обновлением"
            git rev-parse HEAD

            echo "Сбрасываем все изменения и обновляем код"
            git fetch origin
            git reset --hard origin/master

            echo "Останавливаем и удаляем старые контейнеры"
            docker-compose down

            echo "Удаляем старые образы"
            docker system prune -af

            echo "Пересобираем и запускаем контейнеры"
            docker-compose up --build -d

            echo "Деплой завершен"

      # Проверка статуса контейнеров
      - name: Check Docker container status
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: 88.218.168.129
          username: root
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /var/www/mywebsite/my-test-cicd || { echo "Folder not found!"; exit 1; }
            echo "Successfully entered directory"
            ls -la  # Проверим, что в папке есть файлы
            docker-compose ps
            docker-compose logs
